name: go_fir_cli build
on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'
          cache: true
      - name: Install dependencies
        run: go get .

      - name: Build 
        run: go build

      - name: show dir
        run: ls -alh
      
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: go_fir_cli
          path: go_fir_cli
        
